stages:
  - build
  - test


test:opensuse-serial:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: build
  script:
    - sh utils/build-serial-opensuse.sh

test:opensuse-serial-test:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: test
  script:
    - sh utils/build-serial-opensuse.sh 
    - make check

test:opensuse-mpi:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: build
  script:
    - sh utils/build-mpi-opensuse.sh

test:opensuse-mpi-test:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: test
  script:
    - sh utils/build-mpi-opensuse.sh
    - make check

test:debian-serial:
  image: drfaustroll/esl:debian-latest
  stage: build
  script:
    - sh utils/build-serial-debian.sh
  artifacts:
    when: on_failure
    paths:
      - src/test-suite.log
    expire_in: 1 week

test:debian-serial-test:
  image: drfaustroll/esl:debian-latest
  stage: test
  script:
    - sh utils/build-serial-debian.sh
    - make check

test:debian-mpi:
  image: drfaustroll/esl:debian-latest
  stage: build
  script:
    - sh utils/build-mpi-debian.sh

test:debian-mpi-test:
  image: drfaustroll/esl:debian-latest
  stage: test
  script:
    - sh utils/build-mpi-debian.sh
    - make check 
