# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Electronic Structure Common Data Format
email: devops@materialsevolution.es
description: > # this means to ignore newlines until "baseurl:"
  The Electronic Structure Common Data Format (ESCDF) Library is an
  implementation of the ESCDF Specifications for an efficient and
  platform-independent exchange of electronic-structure-related data
  between different software packages and/or computers. It supports
  parallel filesystems and is based on HDF5.
baseurl: "/esl/escdf" # the subpath of your site, e.g. /blog
url: "http://www.e-cam2020.eu" # the base hostname & protocol for your site
twitter_username: ElStructLib
github_username:  ElectronicStructureLibrary

# Build settings
markdown: kramdown
exclude: ["README.md"]
